# Generated by Django 5.0.1 on 2024-01-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='name',
        ),
    ]
