# Generated by Django 4.2.3 on 2024-02-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
